apiVersion: v1
kind: ConfigMap
metadata:
  name: icp4d-open-api-configmap
  labels:
    app: {{ template "icp4d-openapi.name" . }}
    chart: {{ template "icp4d-openapi.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    run: runtimes-def-configmap
    icpdata_addon: "true"
data:
  init: |
    ls -lah
  nginx.conf: |
    location /icp4d-api/ {
      proxy_set_header Host $host;
      proxy_pass http://icp4d-open-api-svc:4009/;
    }