apiVersion: v1
kind: Service
metadata:
  name: icp4d-open-api-svc
  labels:
    app.kubernetes.io/name: {{ include "icp4d-openapi.name" . }}
    helm.sh/chart: {{ include "icp4d-openapi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: goserver
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "icp4d-openapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
